#!/bin/bash

################################################################################
# Author: T. Cameron Waller
# Date, first execution: __ March 2023
# Date, last execution: __ March 2023
# Review: TCW; ___
################################################################################
# Note

# https://www.cog-genomics.org/plink/1.9/score
# https://www.cog-genomics.org/plink/2.0/score


# The output file of PLINK2 "score" command is in ".sscore" format.
# https://www.cog-genomics.org/plink/2.0/formats#sscore


# Arguments
# 1. SNP effect weights
# 2. genotypes (have to be in VCF?)
#

# TODO: TCW; 15 March 2023
# 1. Do I need a format translation script?
# 2.

################################################################################
################################################################################
################################################################################

# Notes...

# BEFORE calling this script, concatenate PRS-CS reports across all chromosomes
# The PRS-CS reports do NOT include header lines.

# This script WILL CALL PLINK2 to apply a linear combination across allelic
# effects to create a polygenic score to represent an entire genotype.


# TODO: TCW; 17 August 2022
# TODO: as the PRS-CSX documentation says, "If polygenic scores are generated by
# TODO: chromosome, use the 'sum' modifier so that they can be combined into a genome-wide score."

# TODO: TCW; 18 August 2022
# TODO: This script will accept a SINGLE file of posterior effect size report from PRS-CSX.
# TODO: This script will call PLINK2 --score for this SINGLE file.
# TODO: This script will need a driver script. Follow pattern of "3_estimate_prscs_allelic_effects.sh"


################################################################################
################################################################################
################################################################################

# 1. I need a "$path_genotype" file


################################################################################
# Organize arguments.
path_source_prscs_allelic_effects=${1} # full path to PRS-CS allelic effects with concatenation across chromosomes
report=${2} # whether to print reports

###########################################################################
# Organize paths.

################################################################################
# Activate Virtual Environment.
# Read private, local file paths.
#echo "read private file path variables and organize paths..."
cd ~/paths
path_plink2=$(<"./tools_plink2.txt")

################################################################################
# Combine allelic effects in PLINK2.

# Format from PRS-CS.
#   chromosome   rsID   base position   A1   A2   effect size


$path_plink2 \
--memory 90000 \
--threads $threads \
--vcf $path_genotype_source_vcf \
--xchr-model 2 \
--score $path_source_prscs_allelic_effects 2 4 header-read no-mean-imputation ignore-dup-ids \
--score-col-nums 6 \
--out report



################################################################################
# Report.
if [[ "$report" == "true" ]]; then
  echo "----------"
  echo "drive_prscs_plink_polygenic_linear_combination_score.sh"
  echo "----------"
  echo "___ report:"
  #cat $path_heritability_report_suffix
  echo "----------"
fi
